// <auto-generated />
namespace Bookmart.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddSubscriptionToSubscriber : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddSubscriptionToSubscriber));
        
        string IMigrationMetadata.Id
        {
            get { return "201905152038078_AddSubscriptionToSubscriber"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
